export const seaShipping =
  "At AAC, we take pride in offering excellent sea shipping services for both full container load (FCL) and less than container load (LCL). Our FCL services are ideal for customers who require the exclusive use of an entire container to ship their goods. This allows for efficient handling of cargo and also reduces the risk of damage to products. On the other hand, our LCL service is perfect for customers with smaller shipments that do not fill up an entire container, as we consolidate multiple LCL shipments into a single container to maximize efficiency. With our extensive experience in sea shipping, we ensure that all cargo is handled with extreme care and safety measures are taken at every stage of the process. Trust us to deliver your goods promptly and securely!";

export const airShipment =
  "Looking for a fast and efficient way to transport your shipment? Look no further than our Air Shipment services! We specialize in delivering packages and parcels all around the world, utilizing the latest technology to ensure that your items arrive at their destination quickly and safely. Whether you need to ship goods for business purposes or simply want to send a personal item, we've got you covered. Our team of highly-trained professionals will work with you every step of the way to make sure that your package is properly packed and labeled, and will provide you with real-time updates on its progress during transit. With our Air Shipment services, you can rest easy knowing that your shipment is in good hands!";

export const localTransportation =
  "Our local transportation services for transporting goods are the perfect solution for businesses and individuals in need of reliable and efficient transportation. With our outsourced of third party fleet of well-maintained vehicles, we guarantee safe and on-time delivery of your goods. Our team of experienced drivers is knowledgeable about the local area, ensuring that your goods are transported through the most efficient routes. We offer flexible scheduling options to accommodate your specific needs, whether you require a one-time shipment or ongoing transportation services. Additionally, our competitive pricing ensures that you receive high-quality service while staying within budget. From small packages to large shipments, we have the experience and resources necessary to handle all of your local transportation needs. Let us take care of moving your goods so you can focus on what matters most – growing your business or enjoying peace of mind that your personal belongings are in good hands.";

export const projectCargoLogistics =
  "At AAC, we take pride in offering top-notch project cargo logistics services that cater to the unique needs of each client. We understand that no two projects are alike and therefore provide tailored solutions for each project. Whether it's transporting heavy equipment or managing complex supply chains, we have the expertise, resources and experience needed to execute successful end-to-end logistics operations. Our team of logistics specialists works closely with clients from start to finish, providing comprehensive planning, coordination, and execution services to ensure timely delivery of cargo without any damage or loss. With a focus on safety, efficiency and cost-effectiveness, we strive to exceed expectations while providing exceptional customer service throughout every step of the process.";

export const atHeavyEquipmentLogistics =
  "At Heavy Equipment Logistics, we offer a comprehensive range of services tailored to meet the needs of clients in need of heavy equipment shipping. Our team is made up of experienced professionals who are ready and willing to tackle any logistical challenge that comes our way. From loading and unloading to transportation and storage, we work hard to ensure that your equipment arrives at its destination safely and on time. We utilize state-of-the-art technology and cutting-edge techniques to make sure each project runs smoothly from start to finish. Plus, with transparent pricing and clear communication every step of the way, you can rest easy knowing that your shipment is in capable hands. Whether you're shipping locally or across borders, trust us for all your heavy equipment logistics needs.";

export const orderManagementFulfillments =
  "We take pride in providing exceptional order management and fulfillment services. From receiving orders to processing, packing, and shipping them out as quickly as possible, we ensure that our clients receive their products in a timely manner. Our team is dedicated to maintaining a clear line of communication with customers, so they can track their orders from start to finish, assured that everything is going smoothly. We also offer customizable packaging options, enabling clients to put their own branding on shipped items and create an unforgettable customer experience. Whether you're sending out one package or 1000, let us handle it all smoothly for you- making sure your products arrive just how you like them- perfectly packed and ready for the occasion!";

export const contractLogistics =
  "At AAC, we are proud to offer top-notch contract logistics services that are tailored to meet your specific needs. Whether you are looking for warehousing, transportation, or other supply chain solutions, we have the expertise and resources to deliver results. Our team of highly trained professionals will work closely with you to develop a customized plan that maximizes efficiency and minimizes costs. We use the latest technology and best practices to ensure that your goods are managed seamlessly from start to finish, so you can focus on growing your business. With our comprehensive range of services and unparalleled customer support, you can trust us to handle all aspects of your logistics operations with professionalism and care.";

export const warehousingStorage =
  "At AAC, we take pride in providing top-notch warehousing and storage solutions for all your needs. Our facilities are equipped with state-of-the-art technology, ensuring optimal safety and security for your valuable goods. We offer various types of storage options, including pallet racking, bulk storage areas, and secure lock-up containers to cater to diverse requirements. Our trained staff is always on hand to provide assistance with inventory management and order fulfillment. Whether you require short-term or long-term storage solutions, we ensure that your goods are safe from damage or theft while under our care. In addition to offering a pristine facility for warehousing and storage services, our flexible pricing plans make it accessible to businesses of all sizes.";

  export const suppliersGoodsInspections = "Your agent in China to check suppliers before ordering and inspect goods in factories or warehouses to ensure that they with your request.";

  export const taxRefund = "At AAC we help our clients to make a tax refund from government directly through our third party agents who are highly trained and professionally legalized for the job.";

  export const paymentGuarantee = "We help our clients to transfer money to suppliers after the goods received in our warehouse and checked for quality according to customer's requirement.";